sudo: required
language: bash
services:
  - docker
before_script:
  - docker build --tag keboola/docker-julipyter .
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  

notifications:
  slack:
    secure: kKbY+/Y/A+n1PvPnEWJlB1Z8w2udMSzukf+9Huoj0AWuqqw5qNP5eDvKcaupn5VFZd8gu6xr7t4S7OoYkzsEd4KrKZIR49f54JFipqXmEcBEbe2zjqG9Wpmo8rNow7VsbB8R5N+Yz3dBxeMhmGzfENsXOMpWrnZKbYFi7+vcxRSckl4Kaqo/bddgNPeAtRwcnP8PEhIAWanRbi7KnJywjWzNEMEgko/EQBMW+Y8Xw6+44loK5ih4w0P9EHSeY91looaI2B6YQfa+GYaavOy3VUUw7jBZL31xMsjmw2Vjyi1Ezk+qqDaRzx+AcDIYnurmuRWecZ8GwJ91On6EvB6Q/DWMKzclCr9PORmQSyvvdfdDEVXbdy4MjmiRu0+BtGtyCGkg3eqZ+5UdHDLbHKjI9rdg3TdALh5RZw3p8/J8Crr35HP84vSbG+J1v0uJACTUOPvwFTW7fjDrQN7Zja7w/ALIjVYJdpi4udPVyJ6yeTLcD83e0HTe7vqoxNvS0U6VhwluA8E0g0KgmcIXSAt9CRPWWVVjtnDkOPKYNVe5K64E66T02JSU3zw92uXB1dC8Nrvpv48LBCQrscndGgRlp0aysBW2eL1FV/Ed6dD0zbG65srFP7ZpY81VX8CkA91I9cpH9ibcPTHjha4rKyArgJfn6lRwxRBejMv3z2S+jLQ=
